### ISSUE TITLE
Team Lutheran Tweetan Code Review

### ISSUE THREAD

**Issue by willflee01** [chrisgnicholas/team_Luther_Tweetan#1]
Hello Team Luther Tweetan:

Overall, great project! From your READMe, it seems you guys have a great direction to take this Project. Would just love to see how you approach coding that policy into existence otherwise.

READMe:
Just for a readability aid, it might be helpful to include a description of all the files in the github. It was a little hard to decipher if these were vestiges of Project 3 or indeed useful for the current project.

code_FINAL:
- I appreciate the comments since it helps point me on where to go. 
- While there are a few demand curves, it might be beneficial to use some of the newer curves professor introduced, such as the Marshallian and Hicks or the deadweight loss curves. 

Deliverables (file):
- In you deliverables file, it seems that you’ve just imported all the files from Project 3 but keep in mind to update them for Project 4 just from a looks-perspective
- It might be helpful to outline what deliverables your code covers for readability in the future.

General: 
In general, it seems you guys are a little behind in terms of the code. Just hopefully, you guys incorporate all the graphs they show in class because the GSIs have been grading those pretty strongly just based on including the graphs provided

You guys seem to be on the right track. Just make sure to cover everything the deliverables ask!

**Comment by chrisgnicholas** [comment]
We considered how to calculate "compensated variation", but the examples from the latest lectures are all centered on price changes associated with a tax or subsidy on food item, versus a subsidy driven by household characteristics. It seemed unclear how to calculate a a 'deadwood cost' of a new item that has no expenditure history. 

But we are able to calculate with is called "indirect_utility" from the regression at the current household income, and what it is at the mean increased level with subsidies. A few cells performing that calculation have been added at the end.

The README is also updated, and the unused notebooks removed.
