### ISSUE TITLE
Jennifer Doudna Code Review

### ISSUE THREAD

**Issue by manutdftw21** [chrisgnicholas/team_Luther_Tweetan#2]
Hey! Similar things to say, the code looks on track. I think utilizing the recent graphs will help boost your overall code. I liked the policy as well, definitely unique. Keep up the good work!

**Comment by chrisgnicholas** [comment]
Thank you for the praise :-)

We considered how to calculate "compensated variation", but the examples from the latest lectures are all centered on price changes associated with a tax or subsidy on food item, versus a subsidy driven by household characteristics.

But we are able to calculate with is called "indirect_utility" from the regression at the current household income, and what it is at the mean increased level with subsidies. A few cells performing that calculation have been added at the end.

**Comment by chrisgnicholas** [comment]
pushed those changes back up
